server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://${DASH_DOMAIN:-dash.maxow.ru}/loki/api/v1/push
    basic_auth:
      username: ${MDASH_PUSH_USER}
      password: ${MDASH_PUSH_PASSWORD}
    external_labels:
      project: mvpn
      app: mvpn

scrape_configs:
  - job_name: mvpn-file-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mvpn-logs
          service: backend
          app: mvpn
          __path__: /app/logs/*.log
