spring:
  application:
    name: mVPN
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: ${TELEGRAM_BOT_USERNAME}

minio:
  url: http://127.0.0.1:9000
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: user-configs