spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/mvpn_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: MvpnProdHikariPool
      maximum-pool-size: 25
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  file:
    name: ${LOGGING_FILE_NAME:/app/logs/mvpn.log}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:}

encryption:
    key: ${ENCRYPTION_KEY}
