spring:
  application:
    name: mVPN
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:mVPN-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: ru.maxow.mvpn.broadcast
            value.default.type: ru.maxow.mvpn.broadcast.BroadcastRequestDto
    template:
      default-topic: ${KAFKA_DEFAULT_TOPIC:mVPN-topic}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        provider:
            keycloak:
              issuer-uri: http://localhost:8040/realms/mID-realm
              jwk-set-uri: http://host.docker.internal:8040/realms/mID-realm/protocol/openid-connect/certs
              authorization-uri: http://localhost:8040/realms/mID-realm/protocol/openid-connect/auth
              token-uri: http://host.docker.internal:8040/realms/mID-realm/protocol/openid-connect/token
              user-info-uri: http://host.docker.internal:8040/realms/mID-realm/protocol/openid-connect/userinfo
        registration:
            keycloak:
                provider: keycloak
                client-id: ${KEYCLOAK_CLIENT_ID}
                client-secret: ${KEYCLOAK_CLIENT_SECRET}
                scope:
                  - openid
                  - profile
                  - email

bot:
  enabled: ${BOT_ENABLED:false}
  token: ${TELEGRAM_BOT_TOKEN}
  username: ${TELEGRAM_BOT_USERNAME}

minio:
  url: http://127.0.0.1:9000
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: user-configs

app:
  kafka:
    topics:
      broadcast: ${KAFKA_BROADCAST_TOPIC:broadcast-requests}
    groups:
      broadcast: ${KAFKA_BROADCAST_GROUP:broadcast-group}