ConfigByVerificationCode:
  get:
    operationId: getConfigByVerificationCode
    summary: Получить конфигурацию по коду верификации
    tags: [Config]
    parameters:
      - name: verificationCode
        in: path
        required: true
        schema:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
    responses:
      200:
        description: Конфигурация успешно получена
        headers:
          profile-title:
            description: Название подписки
            schema:
              type: string
          profile-description:
            description: Описание подписки
            schema:
              type: string
          support-url:
            description: Ссылка на поддержку
            schema:
              type: string
          profile-web-page-url:
            description: Страница подписки
            schema:
              type: string
          profile-update-interval:
            description: Интервал обновления (часы)
            schema:
              type: string
          subscription-userinfo:
            description: Информация о подписке пользователя
            schema:
              type: string
          Cache-Control:
            description: Управление кешированием
            schema:
              type: string
        content:
          text/plain:
            schema:
              type: string
              example: "fcarpouhfgnoa9e87fhgzqsjweo987dzwghenfmr9jcx8qej0aOFASWZ687RFYXHWYTAWJ8SXQ8"
          application/json:
            schema:
              type: string
              example: |-
                {"format":"json","nodes":[...]}
      '400':
        description: Ошибка валидации данных или некорректный запрос
        content:
          text/plain:
            schema:
              type: string
              example: "Verification code is invalid"
      '401':
        description: Требуется аутентификация
        content:
          text/plain:
            schema:
              type: string
              example: "Unauthorized"
      '403':
        description: Доступ запрещен
        content:
          text/plain:
            schema:
              type: string
              example: "Forbidden"
      '404':
        description: Ресурс не найден
        content:
          text/plain:
            schema:
              type: string
              example: "Verification code not found"
      '503':
        description: Сервис временно недоступен
        content:
          text/plain:
            schema:
              type: string
              example: "Service Temporarily Unavailable"
